export const locations = {
  'united-states': { name: 'United States', title: 'Business evolution for ambitious US companies.', context: 'We help growing US companies reduce operational overhead, connect fragmented tools, and build systems that scale without adding unnecessary complexity.', focus: ['AI and workflow automation','Custom operational software','Customer and client portals','Data and reporting systems'] },
  serbia: { name: 'Serbia', title: 'Built in Serbia. Designed for global standards.', context: 'Bevox works closely with Serbian companies that are ready to replace manual administration, spreadsheets, and disconnected software with modern operational systems.', focus: ['Business process automation','Internal business systems','Digital platforms','AI adoption and integration'] },
  austria: { name: 'Austria', title: 'Connected systems for precise, efficient operations.', context: 'We support Austrian businesses with secure, practical automation and custom systems designed around established processes and measurable operational value.', focus: ['Process modernization','System integrations','Operational dashboards','Custom software'] },
  germany: { name: 'Germany', title: 'Operational software built for reliability.', context: 'For German companies, we focus on process clarity, maintainable systems, structured data, and automation that fits real operational requirements.', focus: ['Workflow engineering','Legacy system modernization','AI-assisted operations','Data integration'] },
  hungary: { name: 'Hungary', title: 'Practical digital evolution across Central Europe.', context: 'We work with Hungarian companies to unify operational data, automate coordination, and build software that supports regional growth.', focus: ['Connected operations','Automation','Client portals','Management reporting'] },
  bulgaria: { name: 'Bulgaria', title: 'Systems for fast-moving regional businesses.', context: 'We help Bulgarian companies modernize workflows, improve visibility, and introduce AI where it creates a clear operational advantage.', focus: ['AI automation','Internal tools','API integrations','Business intelligence'] },
  malta: { name: 'Malta', title: 'Digital operations for international businesses.', context: 'We support Malta-based and internationally oriented companies with digital platforms, automated workflows, and connected operational infrastructure.', focus: ['Digital platforms','Compliance workflows','Customer operations','Custom business systems'] },
} as const;

export type LocationSlug = keyof typeof locations;
